### ISSUE TITLE
Package managers and package repositories for C/C++

### ISSUE THREAD

**Issue by jnareb** [szabgab/code-maven.com#115]
The C++ language does not come with an integrated package manager to deal with external dependencies of a project. However, there exists various third party package managers for C++ with their package repositories:

- [Conan](https://conan.io/) with [ConanCenter](https://conan.io/center/), with 867 packages
- [build2](https://build2.org/) with [cppget](https://cppget.org/), with 83 packages
- [Meson](https://mesonbuild.com/) with [Wrap DB](https://wrapdb.mesonbuild.com/), with 163 packages (recipes)
- [vcpkg](https://github.com/microsoft/vcpkg) from Microsoft with [vcpkg](https://vcpkg.io/en/packages.html), with 1656 packages
- ...

**Comment by szabgab** [comment]
Included. Thanks
