### ISSUE TITLE
How to refresh page and show new pdf files and erasing old files from webpage ?

### ISSUE THREAD

**Issue by kenil22** [szabgab/code-maven.com#158]
https://code-maven.com/flask-upload-multiple-files

When we upload new pdf files , pdf files still remain on the website and new ones get added. Is there any alternate logic to update  page and show only new pdf files .

**Comment by szabgab** [comment]
How do you know that the newly uploaded pdf file should be a replacement?
If there are already multiple pdf files on the server, how do you know which one to replace?

**Comment by szabgab** [comment]
Closing for lack of reply.
