### ISSUE TITLE
Code Maven Pro link does not work

### ISSUE THREAD

**Issue by medicinman7** [szabgab/code-maven.com#167]
On the https://code-maven.com/pm/account  page and I select the button "9 USD Per month.", I get direct to https://www.paypal.com/webapps/mpp/page-not-found

**Comment by szabgab** [comment]
Thanks for letting me know. I need to remove all references to the Pro possibility as I have published all the content to the public so there is nothing in the pro right now. People who are interested to support my work are invited to various ways listed here: https://szabgab.com/support.html

**Comment by szabgab** [comment]
I have remove all the account-related links - I hope so new people won't register and won't look for the pro account. I hope.

Thanks and sorry for the inconvenience!

**Comment by medicinman7** [comment]
No worries. Thank you.
