### ISSUE TITLE
Episode date format invalid / Invalid feed.

### ISSUE THREAD

**Issue by morrisonj** [szabgab/code-maven.com#39]
Not sure if this is the right place to contact you but I'm trying to submit your podcast feed http://code-maven.com/rss/cmos to: http://www.pocketcasts.com/submit

I get the following errors:

> Episode date format invalid.
> Solution: Change the pubDate tag to use the following format:
> `<pubDate>Wed, 03 Nov 2015 19:18:00 GMT</pubDate>`
> 
> Invalid feed
> Your podcast doesn’t seem to contain any episode files. Try adding an episode under the enclosure URL tag, eg: 
> `<enclosure url="http://example.com/podcast/episode1.mp3" length="5860687” type=“audio/mpeg"/>`

Really enjoying the podcast but I would like to subscribe with Pocket Casts so I don't miss an episode.

**Comment by szabgab** [comment]
This is totally the right place though the actual source code of the site is here: https://github.com/szabgab/Perl-Maven  I'll look into it soon.

**Comment by szabgab** [comment]
I think I've fixed it. Please check.

**Comment by morrisonj** [comment]
Thanks. I've checked again and it's giving the same error. I had a look at the feed and noticed a couple of things that may need changing to make it work:

pubDate is missing a comma after the day:
`Sat Sep  3 09:19:24 2016 GMT`
should be
`Sat**,** Sep  3 09:19:24 2016 GMT`

enclosure type is different:
`<enclosure url="http://code-maven.com/media/cmos-3-joel-berger-mojolicious.mp3" length="23645783" type="audio/x-mp3" />`
should be
`<enclosure url="http://code-maven.com/media/cmos-3-joel-berger-mojolicious.mp3" length="23645783" type="**audio/mpeg**" />`

Pocket casts is quite picky with its feed formatting it would seem :)

**Comment by szabgab** [comment]
Does this feed work: http://feeds.5by5.tv/changelog ?

**Comment by morrisonj** [comment]
It's already in their directory so it won't let me add it again:

> Your feed is already in Pocket Casts!

**Comment by szabgab** [comment]
Could you check the CMOS feed again?

**Comment by morrisonj** [comment]
It worked! Thankyou!

> Your feed was successfully added!
> 
> Code Maven
> Gabor Szabo
> CMOS - Code Maven Open Source podcast

**Comment by szabgab** [comment]
Phew. 😄
